### PR TITLE
Set Window icon

### PR DESCRIPTION
**Pull request by prashantsengar**
Added the function to add window icon

### CODE REVIEW

**Comment by prashantsengar** [comment]
I have set the Window icon as mentioned in issue #15 
@jancborchardt please have a look and merge the PR if it fine.

**Comment by jancborchardt** [comment]
@prashantsengar nice addition! I don’t have a Windows machine to test, could you show a screenshot? :)

**Comment by prashantsengar** [comment]
Here it is
image

**Comment by jancborchardt** [comment]
Very cool! Sorry for the late reply @prashantsengar, I was on vacation for 2 weeks, back now. :)

**Pull request merged**
